spring:
  application:
    name: eureka-cluster
    
#配置双节点，相互注册
#---
#spring:
#  profiles: peer1
server:
  port: 8761
eureka:
  client:
    registerWithEureka: false
    fetchRegistry: false
    serviceUrl:
      defaultZone: http://localhost:${server.port}/eureka/
#---    
#spring:
#  profiles: peer2
#server:
#  port: 8762
#eureka:
#  client:
#    serviceUrl:
#      defaultZone: http://localhost:${server.port}/eureka/


security:
  basic:
    enabled: true  #开启基于HTTP basic的认证
  user:
    name: wyc
    password: 123456
    
